version: '3.7'

services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./env:/money-book/env
      - ./src:/money-book/src
    ports:
      - 3000:3000

  database-server:
    # platform: linux/x86_64 # mac(m1) docker에서는 1회성으로 리눅스 환경 설정
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'money-book'
      MYSQL_ROOT_PASSWORD: '2222'
      MYSQL_TCP_PORT: 3307
      TZ: 'Asia/Seoul'
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+09:00',
        '--default-authentication-plugin=mysql_native_password',
      ]
    ports:
      - 3307:3307
